management:
  endpoints:
    web:
      exposure:
        include: "*"
#      security:
#        enable: false

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效


info:
  company.name: org.jiang
  company.address: 四川成都
  description: ${spring.application.name}
